# server port config
# first-project 에서는 server.port:8800으로 썼으나 여기에서는 이러한 방식으로 쓰는 이유는
# server의 하위에 정의할 수 있는 내용이 많아 추가적으로 작성할때 더욱 간결하게 코드를 작성하기 위해
server:
  port: 8006
  
# oracle driver config
# DB연결정보
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@KHCulture_high?TNS_ADMIN=C:\\Users\\lje_9\\git\\KHculture_final\\Oracle_Wallet
    username: admin
    password:  KHCulture2021
    hikari:
     connection-test-query: select sysdate from dual
    # driver-class-name: oracle.jdbc.OracleDriver
    # url: jdbc:oracle:thin:@localhost:1521:xe
    # username: kh_Final
    # password: khfinal
  servlet:
    multipart:
      max-file-size:
        10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: #이메일 계정
    password: #이메일 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # 2021.12.26 추가 - oauth 사용시 반드시 작성해야하는 부분이다
  profiles:    include: oauth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:  c62fd21fe68a0f32a4975d8a5b495742
            redirect-uri: http://localhost:8006/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:    show-sql: true
    hibernate:      ddl-auto: create
   
# mybatis config
mybatis:
 mapper-locations: mappers/**/*.xml
 
# logging level (root level - 전역 설정)
logging:
  level:
    root: info

# logging level (package level - 지역 설정)
    '[com.kh.khculture.book]': trace

custom:
  path:
    upload-images: 'C:\Users\lje_9\git\KHCulture\src\main\resources\uploadFiles/'